// Fallback data representing the complete seeded Voices of Vehari site
// Used automatically when the backend API is offline or unreachable

export const fallbackData = {
  settings: {
    site_name: 'Voices of Vehari',
    tagline: 'Enhancing English Proficiency through Multilingual Podcasting and Cultural Storytelling.',
    campus: 'COMSATS University Islamabad, Vehari Campus',
    address: 'Mailsi Road, Off Multan Road, Peer Murad, Vehari, Punjab, Pakistan',
    contact_email: 'info@voicesofvehari.edu.pk',
    contact_phone: '+92 (0) 67 3602803',
    pi_name: 'Dr. Muhammad Imran Saeed',
    copi_name: 'Nazish Malik',
    logo_url: '/assets/voices_logo.png',
    footer_text: 'Enhancing English Proficiency through Multilingual Podcasting and Cultural Storytelling.',
    footer_copyright: 'Voices of Vehari · COMSATS University Islamabad, Vehari Campus',
    meta_title: 'Voices of Vehari | Multilingual Podcasting & Cultural Storytelling',
    meta_description: 'A research & community storytelling initiative connecting English language development with local languages, stories and lived experiences of Vehari.',
  },

  hero: {
    kicker: 'A research & community storytelling initiative',
    title: 'Voices of Vehari',
    lead_strong: 'Enhancing English Proficiency through Multilingual Podcasting and Cultural Storytelling.',
    lead_body: 'A context-based learning project that brings English, local languages, community voices and the cultural heritage of Vehari together through simple, accessible podcasts and stories.',
    primary_btn_text: 'Explore Podcasts',
    primary_btn_url: '#podcasts',
    secondary_btn_text: 'Start Learning',
    secondary_btn_url: '#learning',
    hero_image_url: '/assets/hero_art.jpeg',
    hero_image_alt: 'Illustration of young people creating podcasts and sharing stories',
    logo_float_url: '/assets/voices_logo.png',
    is_active: true,
  },

  statistics: [
    { value: '12', label: 'Months of project activity', sort_order: 1 },
    { value: '20', label: 'University students in the podcast intervention', sort_order: 2 },
    { value: '15', label: 'Community participants', sort_order: 3 },
    { value: '12', label: 'Practice group sessions', sort_order: 4 },
  ],

  cards: {
    home_idea: [
      {
        icon: '🎙️',
        title: 'Multilingual Podcasting',
        description: 'Use simple podcasts with English alongside local languages such as Punjabi and Saraiki to provide authentic, accessible language input.',
      },
      {
        icon: '📖',
        title: 'Cultural Storytelling',
        description: 'Use local folklore, historical narration, customs and rural experiences as meaningful contexts for language learning.',
      },
      {
        icon: '📚',
        title: 'English Learning',
        description: 'Turn every conversation into opportunities to practise listening, speaking and vocabulary through questions, word lists and speaking prompts.',
      },
    ],

    about_challenge: [
      {
        title: 'Conventional learning',
        description: 'Rote learning, grammar drills and standard textbooks may not always sustain learner attention or support cultural and linguistic identities.',
      },
      {
        title: 'Limited authentic input',
        description: 'In EFL contexts, learners can have few opportunities to hear and use English naturally outside class.',
      },
      {
        title: 'Underexplored context',
        description: 'The proposal identifies a need for more empirical research on podcasting in multilingual, rural and culturally specific settings such as Vehari.',
      },
    ],

    research_objective: [
      {
        icon: '01',
        title: 'Listening & speaking',
        description: 'Assess the impact of multilingual podcasting on improving English listening and speaking proficiency among EFL learners in Vehari.',
      },
      {
        icon: '02',
        title: 'Vocabulary & culture',
        description: 'Evaluate the role of cultural storytelling in enhancing vocabulary acquisition and cultural awareness.',
      },
      {
        icon: '03',
        title: 'Perceptions',
        description: 'Explore students\' and teachers\' perceptions of multilingual podcasts as a tool for English language instruction.',
      },
      {
        icon: '04',
        title: 'Scalable model',
        description: 'Develop a scalable model for integrating podcasting and cultural storytelling into EFL curricula in multilingual settings.',
      },
    ],

    learning_resource: [
      {
        icon: '🎧',
        title: 'Listening Practice',
        description: 'Listen to a podcast, identify key ideas and answer comprehension questions.',
        bullets: ['Main-idea questions', 'Detail questions', 'Listening reflection'],
      },
      {
        icon: '🗣️',
        title: 'Speaking Practice',
        description: 'Use episode questions and local topics to encourage guided English conversation.',
        bullets: ['Opinion prompts', 'Follow-up questions', 'Short speaking tasks'],
      },
      {
        icon: '📖',
        title: 'Vocabulary',
        description: 'Build practical word lists from authentic conversations and cultural stories.',
        bullets: ['English word', 'Local-language meaning', 'Example sentence'],
      },
      {
        icon: '💬',
        title: 'Conversation Guides',
        description: 'Simple support for introducing guests, asking questions, following up and closing interviews.',
      },
      {
        icon: '🌍',
        title: 'Multilingual Learning',
        description: 'Use Punjabi, Saraiki and other familiar linguistic resources to support understanding while developing English.',
      },
      {
        icon: '👩‍🏫',
        title: 'Teacher Resources',
        description: 'Lesson ideas, discussion questions, vocabulary activities, assessment templates and the future how-to guide.',
      },
    ],

    gallery_theme: [
      { title: 'Podcast Recording', description: 'Add real recording-session photographs here.' },
      { title: 'University Sessions', description: 'Document student practice, mentor training and learning activities.' },
      { title: 'Community Sessions', description: 'Document the six planned community-centre practice sessions and engagement activities.' },
      { title: 'Behind the Scenes', description: 'Show planning, interviewing, editing and resource creation.' },
      { title: 'Events', description: 'Add photographs from the university and community dissemination events.' },
      { title: 'Campus & Community', description: 'Capture the places and people that give the project its local identity.' },
    ],

    outcome_item: [
      { tag: '01', title: 'Better English', description: 'Improvement in English speaking, listening and vocabulary among the 20 university students, assessed before, during and after podcast sessions.' },
      { tag: '02', title: 'Community confidence', description: 'Evidence of increased confidence in using English among 15 community participants through group discussions and practice sessions.' },
      { tag: '03', title: 'Online resource collection', description: 'A free collection of podcasts, word lists and bilingual stories accessible to students, teachers and community members.' },
      { tag: '04', title: 'Research output', description: 'A journal article and a presentation at a local or regional conference to share the project\'s findings.' },
      { tag: '05', title: 'Repeatable teaching plan', description: 'An accessible guide showing how teachers and community leaders can use podcasts and local stories to teach English.' },
    ],

    news_event: [
      { tag: 'Planned', title: 'Student Mentor Training', description: 'Document the training of undergraduate student mentors who will support English learning through local languages.' },
      { tag: 'Planned', title: 'University Practice Sessions', description: 'Six group sessions at the university where participants listen, speak English and discuss local stories.' },
      { tag: 'Planned', title: 'Community Practice Sessions', description: 'Six sessions at community centres to extend the learning intervention beyond campus.' },
      { tag: 'Planned', title: 'Podcast Releases', description: 'Publish new conversations and stories with their transcripts and learning activities.' },
      { tag: 'Planned', title: 'University Dissemination Event', description: 'Present project results to students, teachers and other stakeholders.' },
      { tag: 'Planned', title: 'Community Dissemination Event', description: 'Share the project\'s learning, stories and results with the wider community.' },
    ],
  },

  podcasts: [
    {
      id: 1,
      title: 'Women Education in Vehari',
      slug: 'women-education-in-vehari',
      guest: 'Dr. Asma Kashif Shehzad',
      host: 'Abdullah',
      description: "A podcast conversation exploring women's education, opportunities and challenges in the local Vehari context.",
      category: 'education',
      tags: ['Education', 'Urdu'],
      audio_url: 'https://actions.google.com/sounds/v1/ambiences/outdoor_ambience.ogg',
      cover_image_url: '/assets/podcast_women_edu.jpeg',
      transcript_url: '#transcript',
      learning_url: '#learning',
      sort_order: 1,
      is_featured: true,
      is_published: true,
    },
    {
      id: 2,
      title: 'Food of Vehari',
      slug: 'food-of-vehari',
      guest: 'Hassan Raza',
      host: 'Abdullah',
      description: 'A local food and culture conversation exploring tastes, traditions and the stories connected with food in Vehari.',
      category: 'food',
      tags: ['Food', 'Culture'],
      audio_url: 'https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg',
      cover_image_url: '/assets/podcast_food.jpeg',
      transcript_url: '#transcript',
      learning_url: '#learning',
      sort_order: 2,
      is_featured: false,
      is_published: true,
    },
    {
      id: 3,
      title: 'Upcoming Local Voices',
      slug: 'upcoming-local-voices',
      guest: 'Community Guests & Youth',
      host: 'Project Team',
      description: 'Future episodes will feature folktales, local customs, rural experiences, youth perspectives and community stories.',
      category: 'culture',
      tags: ['Culture', 'Multilingual'],
      audio_url: null,
      cover_image_url: '/assets/podcast_upcoming.jpeg',
      transcript_url: '#transcript',
      learning_url: '#learning',
      sort_order: 3,
      is_featured: false,
      is_published: true,
    },
  ],

  stories: [
    {
      id: 1,
      title: 'Voices from local folklore',
      slug: 'voices-from-local-folklore',
      category_tag: 'Folklore',
      excerpt: 'Short bilingual stories rooted in the oral traditions of Vehari, followed by English vocabulary and discussion prompts.',
      author: 'Voices of Vehari Research Team',
      is_published: true,
    },
    {
      id: 2,
      title: 'Local customs & traditions',
      slug: 'local-customs-traditions',
      category_tag: 'Customs',
      excerpt: 'Stories that explain how community practices, celebrations and everyday traditions are experienced and remembered.',
      author: 'Voices of Vehari Research Team',
      is_published: true,
    },
    {
      id: 3,
      title: 'Stories of rural life',
      slug: 'stories-of-rural-life',
      category_tag: 'Rural life',
      excerpt: 'Context-rich narratives about work, family, community and the environments in which learners live.',
      author: 'Voices of Vehari Research Team',
      is_published: true,
    },
    {
      id: 4,
      title: 'Historical narration',
      slug: 'historical-narration',
      category_tag: 'History',
      excerpt: 'Locally relevant historical accounts presented in accessible language and connected to English learning activities.',
      author: 'Voices of Vehari Research Team',
      is_published: true,
    },
    {
      id: 5,
      title: 'Food & cultural memory',
      slug: 'food-cultural-memory',
      category_tag: 'Food',
      excerpt: 'Food stories that connect language with tastes, places, family traditions and local identity.',
      author: 'Voices of Vehari Research Team',
      is_published: true,
    },
    {
      id: 6,
      title: 'Young voices',
      slug: 'young-voices',
      category_tag: 'Youth',
      excerpt: 'Student and youth perspectives that document aspirations, learning experiences and life in contemporary Vehari.',
      author: 'Voices of Vehari Research Team',
      is_published: true,
    },
  ],

  gallery: [
    { id: 1, title: 'Voices of Vehari project poster', caption: 'Project Visual Presentation', image_url: '/assets/gallery_poster.jpeg', alt_text: 'Voices of Vehari project poster' },
    { id: 2, title: 'Illustration representing podcasting and storytelling', caption: 'Creative Media Design', image_url: '/assets/gallery_storytelling.jpeg', alt_text: 'Illustration representing podcasting and storytelling' },
    { id: 3, title: 'COMSATS Vehari project visual', caption: 'Campus Context', image_url: '/assets/gallery_campus.jpeg', alt_text: 'COMSATS Vehari project visual' },
    { id: 4, title: 'Illustration of student podcast contributors', caption: 'Youth Engagement', image_url: '/assets/gallery_students.jpeg', alt_text: 'Illustration of student podcast contributors' },
    { id: 5, title: 'Project poster visual', caption: 'Outreach & Documentation', image_url: '/assets/gallery_event.jpeg', alt_text: 'Project poster visual' },
    { id: 6, title: 'Podcast and storytelling illustration', caption: 'Media In Action', image_url: '/assets/gallery_recording.jpeg', alt_text: 'Podcast and storytelling illustration' },
  ],

  team: [
    { id: 1, name: 'Dr. Muhammad Imran Saeed', role_category: 'leadership', designation: 'Principal Investigator · Principal Author', initials: 'IS' },
    { id: 2, name: 'Nazish Malik', role_category: 'leadership', designation: 'Co-Principal Investigator · Co-author', initials: 'NM' },
    { id: 3, name: 'Muhammad Shoaib', role_category: 'mentor', designation: 'Mentor', initials: 'MS' },
    { id: 4, name: 'Muhammad Rashid', role_category: 'mentor', designation: 'Mentor', initials: 'MR' },
    { id: 5, name: 'Muhammad Irshad', role_category: 'mentor', designation: 'Mentor', initials: 'MI' },
    { id: 6, name: 'Khansa Saeed', role_category: 'student', designation: 'Student Team', initials: 'KS' },
    { id: 7, name: 'Maha Anwar', role_category: 'student', designation: 'Student Team', initials: 'MA' },
    { id: 8, name: 'Muhammad Suleman', role_category: 'student', designation: 'Student Team', initials: 'MS' },
    { id: 9, name: 'Noor Fatima', role_category: 'student', designation: 'Student Team', initials: 'NF' },
    { id: 10, name: 'Noreen Nehsat', role_category: 'student', designation: 'Student Team', initials: 'NN' },
    { id: 11, name: 'Aleeza Khadim', role_category: 'student', designation: 'Student Team', initials: 'AK' },
    { id: 12, name: 'Bassri Sattar', role_category: 'student', designation: 'Student Team', initials: 'BS' },
    { id: 13, name: 'Abdullah', role_category: 'contributor', designation: 'Podcast Host', initials: 'AA' },
    { id: 14, name: 'Hassan Raza', role_category: 'contributor', designation: 'Featured Guest · Food & Culture', initials: 'HR' },
    { id: 15, name: 'Dr. Asma Kashif Shehzad', role_category: 'contributor', designation: 'Featured Guest · Women\'s Education', initials: 'AK' },
  ],

  team_by_role: {
    leadership: [
      { id: 1, name: 'Dr. Muhammad Imran Saeed', role_category: 'leadership', designation: 'Principal Investigator · Principal Author', initials: 'IS' },
      { id: 2, name: 'Nazish Malik', role_category: 'leadership', designation: 'Co-Principal Investigator · Co-author', initials: 'NM' },
    ],
    mentor: [
      { id: 3, name: 'Muhammad Shoaib', role_category: 'mentor', designation: 'Mentor', initials: 'MS' },
      { id: 4, name: 'Muhammad Rashid', role_category: 'mentor', designation: 'Mentor', initials: 'MR' },
      { id: 5, name: 'Muhammad Irshad', role_category: 'mentor', designation: 'Mentor', initials: 'MI' },
    ],
    student: [
      { id: 6, name: 'Khansa Saeed', role_category: 'student', designation: 'Student Team', initials: 'KS' },
      { id: 7, name: 'Maha Anwar', role_category: 'student', designation: 'Student Team', initials: 'MA' },
      { id: 8, name: 'Muhammad Suleman', role_category: 'student', designation: 'Student Team', initials: 'MS' },
      { id: 9, name: 'Noor Fatima', role_category: 'student', designation: 'Student Team', initials: 'NF' },
      { id: 10, name: 'Noreen Nehsat', role_category: 'student', designation: 'Student Team', initials: 'NN' },
      { id: 11, name: 'Aleeza Khadim', role_category: 'student', designation: 'Student Team', initials: 'AK' },
      { id: 12, name: 'Bassri Sattar', role_category: 'student', designation: 'Student Team', initials: 'BS' },
    ],
    contributor: [
      { id: 13, name: 'Abdullah', role_category: 'contributor', designation: 'Podcast Host', initials: 'AA' },
      { id: 14, name: 'Hassan Raza', role_category: 'contributor', designation: 'Featured Guest · Food & Culture', initials: 'HR' },
      { id: 15, name: 'Dr. Asma Kashif Shehzad', role_category: 'contributor', designation: 'Featured Guest · Women\'s Education', initials: 'AK' },
    ],
  },

  timeline: [
    {
      phase_number: 1,
      duration: 'Months 1–3',
      title: 'Getting Ready',
      paragraphs: [
        'Learn what people need: discuss with 30 university students and 15 community members through simple questionnaires or group interviews.',
        'Helpers training: train 10–15 undergraduate students to become mentors who can support English learning using local languages such as Punjabi and Saraiki.',
        'Easy resources: develop word lists, brief bilingual stories and conversation guides.',
        'Venues: establish learning venues through a local university and two community centres such as a school or library.',
      ],
    },
    {
      phase_number: 2,
      duration: 'Months 4–9',
      title: 'Learning with Podcasts',
      paragraphs: [
        'Podcast sessions: use weekly podcasts with 20 university students and 15 community residents. Episodes combine English learning with local stories such as folktales or customs in Punjabi and Saraiki. Each podcast includes simple questions, vocabulary training and suggestions for speaking.',
        'Practice groups: conduct 12 group sessions — 6 at the university and 6 at community centres — where participants listen, speak English and discuss local stories.',
        'Assess progression: use simple tests before, during and after sessions to examine progress in English skills such as clear speaking and understanding conversations.',
      ],
    },
    {
      phase_number: 3,
      duration: 'Months 10–12',
      title: 'Sharing & Finishing Up',
      paragraphs: [
        'Resource collection: bring podcasts, word lists and stories together on a free digital resource page.',
        'Two events: present project results at one university event and one community-centre event.',
        'How-to guide: produce a short, accessible guide for teachers and community leaders on using podcasts and local stories to teach English.',
      ],
    },
  ],

  references: [
    { author: 'Rosell-Aguilar (2013)', contribution: 'Podcasting for language learning and its potential in technology-supported instruction.' },
    { author: 'Hassan & Hoon (2013)', contribution: 'Review of podcast applications in language learning.' },
    { author: 'Cenoz & Gorter (2013)', contribution: 'Plurilingual approaches and flexible boundaries between languages.' },
    { author: 'Creese & Blackledge (2010)', contribution: 'Translanguaging as a pedagogy for multilingual classrooms.' },
    { author: 'Byram (1997)', contribution: 'Intercultural communicative competence and learning across cultural differences.' },
    { author: 'Kramsch (1993)', contribution: 'Context and culture in language teaching.' },
    { author: 'Vandergrift & Goh (2012)', contribution: 'Teaching and learning second-language listening.' },
    { author: 'Yeh, Chang & Yeh (2021)', contribution: 'Mobile-assisted language learning and listening skill development.' },
  ],

  teacherGuide: {
    hero: {
      heading: 'Teacher Guide',
      subtitle: 'Practical resources and classroom ideas for teaching English through the voices, stories and experiences of Vehari.',
      intro: 'The Teacher Guide provides practical classroom resources, activity ideas and teaching strategies that connect English learning with local culture, everyday experiences and student voices.',
      primaryCta: 'Explore Teaching Resources',
      secondaryCta: 'Browse Classroom Ideas',
    },
    benefits: [
      {
        icon: '📖',
        title: 'Local Stories',
        description: 'Use familiar stories and community experiences as reading and discussion material.',
      },
      {
        icon: '🎙️',
        title: 'Speaking Practice',
        description: 'Turn local topics into pair and group speaking activities.',
      },
      {
        icon: '📚',
        title: 'Vocabulary Building',
        description: 'Teach useful English vocabulary through familiar places, people and traditions.',
      },
      {
        icon: '✍️',
        title: 'Writing Activities',
        description: 'Help students transform personal and local experiences into short English texts.',
      },
      {
        icon: '💡',
        title: 'Critical Thinking',
        description: 'Encourage students to compare, discuss and reflect on cultural experiences.',
      },
    ],
    categories: ['All', 'Lesson Ideas', 'Speaking', 'Writing', 'Reading', 'Vocabulary', 'Student Engagement'],
    resources: [
      {
        id: 1,
        title: 'Teaching English Through Local Stories',
        category: 'Lesson Ideas',
        excerpt: 'A practical approach to using local stories and community experiences to develop reading, vocabulary and discussion skills.',
        time: '30–45 minutes',
        level: 'Intermediate',
        details: {
          objective: 'Develop contextual reading comprehension, thematic vocabulary, and communicative interaction using local Vehari folk narratives.',
          materials: ['A short printed folk narrative or audio clip', 'Guided reading sheet with vocabulary list', 'Discussion cue cards'],
          steps: [
            'Warm-up (5 mins): Ask students if they know any oral folktales passed down by grandparents in Vehari.',
            'Vocabulary Preview (8 mins): Pre-teach 5-6 key English terms using pictures and local language equivalents (Saraiki/Punjabi).',
            'Active Reading / Listening (12 mins): Students read or listen to the local narrative in pairs, identifying characters and challenges.',
            'Paired Discussion (10 mins): Students answer 3 open-ended comprehension prompts regarding the story message.',
            'Reflection & Wrap-up (5 mins): Brief teacher-led plenary summarizing how cultural themes connect to student lives.',
          ],
        },
      },
      {
        id: 2,
        title: 'Using Cultural Traditions for Speaking Practice',
        category: 'Speaking',
        excerpt: 'Classroom activities that help students discuss local traditions while practicing useful English expressions and conversation skills.',
        time: '25–40 minutes',
        level: 'Beginner–Intermediate',
        details: {
          objective: 'Enhance oral fluency, question-formation, and communicative confidence through peer interviews about seasonal festivals and family traditions.',
          materials: ['Conversation starter strips', 'Sentence frame cards (e.g., "In our family, we usually...", "The most special part is...")'],
          steps: [
            'Brainstorming (5 mins): Elicit local celebrations, harvests, and gatherings onto the board.',
            'Sentence Patterns (8 mins): Model question forms (e.g., "How do you celebrate...?", "What foods are prepared?").',
            'Speed Mingling (15 mins): Students circulate and interview two peers about their favourite custom in English.',
            'Class Sharing (8 mins): Invite volunteer pairs to summarize their partner\'s answers to the class.',
          ],
        },
      },
      {
        id: 3,
        title: 'From Personal Experience to English Writing',
        category: 'Writing',
        excerpt: 'A step-by-step classroom activity that helps students turn everyday experiences into short descriptive English paragraphs.',
        time: '40–50 minutes',
        level: 'Intermediate',
        details: {
          objective: 'Guide learners from oral recollection to structured paragraph drafting with sensory vocabulary and transitional phrases.',
          materials: ['Sensory word bank (sight, sound, smell, feel)', 'Paragraph template with topic sentence, supporting details, and conclusion'],
          steps: [
            'Experience Recall (7 mins): Students write down 4 memories of a visit to the local bazaar or rural fields.',
            'Sensory Mapping (10 mins): Students map English adjectives to describe sounds, smells, and colors from their memory.',
            'Drafting (15 mins): Guided drafting of a 5-6 sentence descriptive paragraph.',
            'Peer Review (10 mins): Exchange with a partner to check past tense verbs and punctuation.',
            'Showcase (8 mins): Wall gallery walk or selected reading aloud.',
          ],
        },
      },
      {
        id: 4,
        title: 'Building Vocabulary from Everyday Life',
        category: 'Vocabulary',
        excerpt: 'Use familiar places, objects and routines from students\' daily lives to introduce and practice new English vocabulary.',
        time: '20–30 minutes',
        level: 'Beginner',
        details: {
          objective: 'Expand everyday conversational and descriptive vocabulary using familiar household, campus, and town items.',
          materials: ['Real-life photo cards of Vehari landmarks and daily objects', 'Vocabulary matching worksheet'],
          steps: [
            'Object Flash (5 mins): Show photos of everyday items/landmarks and ask for their English names.',
            'Concept Check (8 mins): Provide definition matching and example sentences in everyday context.',
            'Pair Challenge (10 mins): Students compose 3 sentences describing their daily walk or commute using the new words.',
            'Review (5 mins): Quick exit-ticket quiz.',
          ],
        },
      },
      {
        id: 5,
        title: 'Discussion Activities for Young Learners',
        category: 'Speaking',
        excerpt: 'Simple discussion prompts designed to encourage students to express opinions, describe experiences and listen to their classmates.',
        time: '25–35 minutes',
        level: 'Beginner–Intermediate',
        details: {
          objective: 'Foster conversational turn-taking, active listening, and opinion phrasing for emerging speakers.',
          materials: ['Opinion scale cards (Agree / Disagree)', 'Topic prompt cards'],
          steps: [
            'Icebreaker (5 mins): Model opinion expressions ("In my opinion...", "I prefer... because...").',
            'Corner Debate (12 mins): Present a simple scenario (e.g., "City life vs. village life in Vehari") and group students.',
            'Group Discussion (10 mins): Each group formulates 2 reasons supporting their viewpoint in English.',
            'Synthesis (5 mins): Reflect on vocabulary learned during the friendly exchange.',
          ],
        },
      },
      {
        id: 6,
        title: 'Using Student Voices in the Classroom',
        category: 'Student Engagement',
        excerpt: 'Strategies for making students active participants by using their own stories, opinions and experiences as learning material.',
        time: '30–45 minutes',
        level: 'Intermediate',
        details: {
          objective: 'Empower student autonomy and agency by developing mini-podcasts and audio interviews in the English classroom.',
          materials: ['Smartphone voice recorder (or pair speaking format)', 'Interview questionnaire worksheet'],
          steps: [
            'Topic Selection (5 mins): Student pairs decide on a topic (e.g. favourite local dish, sports hero, memory).',
            'Question Prep (10 mins): Pairs draft 3 open-ended interview questions in English.',
            'Mock Recording (15 mins): One student acts as host, the other as guest, practicing English interview etiquette.',
            'Feedback (10 mins): Peers give two compliments and one gentle suggestion for pronunciation.',
          ],
        },
      },
    ],
    featuredActivity: {
      title: 'Tell Your Story',
      purpose: 'Help students practice speaking and narrative skills by sharing a familiar personal or local experience.',
      time: '35 minutes',
      level: 'Intermediate',
      objectives: [
        'Practice past tense',
        'Improve speaking confidence',
        'Build descriptive vocabulary',
        'Develop listening skills',
      ],
      steps: [
        'Choose a familiar experience (family event, visit, trip, or school memory).',
        'Write 5–7 keywords in English related to the event.',
        'Prepare a short 1–2 minute story with a clear beginning, middle, and end.',
        'Share the story with a partner in English.',
        'Ask and answer two follow-up questions with your partner.',
        'Present the story or your partner\'s story to the class.',
      ],
      teacherTip: 'Encourage students to choose experiences from their own community, family, school or daily life.',
    },
    strategies: [
      {
        num: '01',
        title: 'Start with Familiar Topics',
        description: 'Begin lessons with places, people and experiences students already understand.',
      },
      {
        num: '02',
        title: 'Encourage Student Voice',
        description: 'Allow students to contribute their own stories and opinions.',
      },
      {
        num: '03',
        title: 'Use Pair Work',
        description: 'Give students opportunities to practice English with classmates before speaking to the whole class.',
      },
      {
        num: '04',
        title: 'Teach Vocabulary in Context',
        description: 'Introduce new words through meaningful stories and situations rather than isolated lists.',
      },
      {
        num: '05',
        title: 'Connect Reading with Speaking',
        description: 'After reading a short text, ask students to discuss it with a partner.',
      },
      {
        num: '06',
        title: 'Make Writing Personal',
        description: 'Let students write about real experiences before moving toward more formal writing tasks.',
      },
    ],
    classroomPrompts: [
      'Imagine you are a local radio presenter. Describe one important issue in your community and suggest one practical solution.',
      'Interview an elder or family member about how traditions or life in Vehari have changed over time, and summarize it in English.',
      'Describe your favorite local dish, bazaar, or festival to a foreign friend using five vivid sensory adjectives.',
      'If you received funding to start an educational community project in Vehari, what would you create and why?',
      'Discuss with your partner: What makes a dedicated teacher or mentor in a rural classroom, and how do they impact students?',
      'Describe an artisan, farmer, or worker in your neighborhood whose craftsmanship or daily hard work inspires you.',
    ],
    lessonPlanTemplate: {
      title: 'Simple Lesson Plan Template',
      description: 'A practical, culturally-responsive lesson structure for classroom English teachers.',
      fields: [
        { label: 'Topic', placeholder: 'e.g. Local Harvests & Markets in Vehari' },
        { label: 'Learning Objective', placeholder: 'e.g. By the end of class, students will be able to describe a market scene using 5 new sensory adjectives.' },
        { label: 'English Skills', placeholder: 'Speaking, Vocabulary, Listening, Reading' },
        { label: 'Vocabulary', placeholder: 'e.g. stall, vendor, barter, fresh, bustling, fragrant' },
        { label: 'Warm-up Activity', placeholder: '5-minute photo prompt & partner brainstorming of familiar local places' },
        { label: 'Main Activity', placeholder: 'Contextual reading or listening from Voices of Vehari story archive' },
        { label: 'Pair/Group Activity', placeholder: 'Role-play interview between local vendor and customer in English' },
        { label: 'Assessment', placeholder: 'Formative observation of peer interaction and 2-minute oral presentation' },
        { label: 'Homework / Follow-up', placeholder: 'Write a 4-sentence reflection on their favorite family custom in English' },
      ],
    },
    tips: [
      'Keep instructions simple, sequential and clear.',
      'Give students silent preparation time before asking them to speak.',
      'Use familiar local examples to introduce difficult grammar concepts.',
      'Encourage students to learn from each other\'s real-life experiences.',
      'Correct important errors gently without interrupting fluency unnecessarily.',
      'Celebrate participation, bravery and effort rather than perfection.',
    ],
  },
};

export default fallbackData;
